{"name": "test_user_login_wrong_password", "status": "passed", "description": "\n        测试用户登录密码错误\n        ", "attachments": [{"name": "log", "source": "c4ff50bd-0f7e-44e2-be00-042ee7780774-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9f6a7d8b-4a03-4504-806b-7dbc1f888590-attachment.txt", "type": "text/plain"}], "start": 1753497028548, "stop": 1753497029556, "uuid": "74951ae3-1d38-456a-ba11-684144083d5b", "historyId": "ec1a1a08e3ce820c370cf7423654099e", "testCaseId": "ec1a1a08e3ce820c370cf7423654099e", "fullName": "user.tests.test_user.TestUserAuthentication#test_user_login_wrong_password", "labels": [{"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "user.tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "zongjunyi.local"}, {"name": "thread", "value": "34675-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "user.tests.test_user"}]}