{"name": "test_user_login_wrong_password", "status": "passed", "description": "\n        测试用户登录密码错误\n        ", "attachments": [{"name": "log", "source": "e84ea40f-5696-4613-8995-56afab46ff41-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c62add9b-164a-4188-bba5-0d1c36103d2c-attachment.txt", "type": "text/plain"}], "start": 1753497214829, "stop": 1753497215555, "uuid": "b6ddb7f0-8551-4cdf-bee9-c2932533d7f4", "historyId": "ec1a1a08e3ce820c370cf7423654099e", "testCaseId": "ec1a1a08e3ce820c370cf7423654099e", "fullName": "user.tests.test_user.TestUserAuthentication#test_user_login_wrong_password", "labels": [{"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "user.tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "zongjunyi.local"}, {"name": "thread", "value": "35500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "user.tests.test_user"}]}