{"name": "test_user_login_wrong_password", "status": "passed", "description": "\n        测试用户登录密码错误\n        ", "attachments": [{"name": "log", "source": "16e9135f-81a7-43e9-a78b-f4e13c01949e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "25a35704-69c7-4c37-a32c-cb9e858ff7f3-attachment.txt", "type": "text/plain"}], "start": 1753497319857, "stop": 1753497320599, "uuid": "2d41a8f3-9427-4c40-a39a-7a9d53a55ad6", "historyId": "ec1a1a08e3ce820c370cf7423654099e", "testCaseId": "ec1a1a08e3ce820c370cf7423654099e", "fullName": "user.tests.test_user.TestUserAuthentication#test_user_login_wrong_password", "labels": [{"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "user.tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "zongjunyi.local"}, {"name": "thread", "value": "36121-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "user.tests.test_user"}]}